"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from pathlib import Path
from typing import Any, Literal

# Constantes de version
VERSION: tuple[int, int, int]

# Constantes XML
NAMESPACES: dict[str, str]
CONTAINER_PATH: str
CONTAINER_XML: str
NCX_XML: str
NAV_XML: str
CHAPTER_XML: str
COVER_XML: str

# Types de média
IMAGE_MEDIA_TYPES: dict[str, str]

# Constantes de types d'items
ITEM_UNKNOWN: Literal[0]
ITEM_IMAGE: Literal[1]
ITEM_STYLE: Literal[2]
ITEM_SCRIPT: Literal[3]
ITEM_NAVIGATION: Literal[4]
ITEM_VECTOR: Literal[5]
ITEM_FONT: Literal[6]
ITEM_VIDEO: Literal[7]
ITEM_AUDIO: Literal[8]
ITEM_DOCUMENT: Literal[9]
ITEM_COVER: Literal[10]
ITEM_SMIL: Literal[11]

class Section:
    title: str
    href: str

    def __init__(self, title: str, href: str = "") -> None: ...

class Link:
    href: str
    title: str
    uid: str | None

    def __init__(self, href: str, title: str, uid: str | None = None) -> None: ...

class EpubException(Exception):
    code: int
    msg: str

    def __init__(self, code: int, msg: str) -> None: ...
    def __str__(self) -> str: ...

class EpubItem:
    """
    Base class for the items in a book.
    """

    # Attributs d'instance
    id: str
    file_name: str
    media_type: str
    content: bytes
    manifest: bool

    def __init__(
        self,
        uid: str | None = None,
        file_name: str = "",
        media_type: str = "",
        content: bytes = b"",
        manifest: bool = True,
    ) -> None:
        """
        :Args:
          - uid: Unique identifier for this item (optional)
          - file_name: File name for this item (optional)
          - media_type: Media type for this item (optional)
          - content: Content for this item (optional)
          - manifest: Manifest for this item (optional)
        """
        ...

    def get_id(self) -> str:
        """
        Returns unique identifier for this item.

        :Returns:
          Returns uid number as string.
        """
        ...

    def get_name(self) -> str:
        """
        Returns name for this item. By default it is always file name but it does not have to be.

        :Returns:
          Returns file name for this item.
        """
        ...

    def get_type(self) -> int:
        """
        Guess type according to the file extension. Might not be the best way how to do it, but it works for now.

        Items can be of type:
          - ITEM_UNKNOWN = 0
          - ITEM_IMAGE = 1
          - ITEM_STYLE = 2
          - ITEM_SCRIPT = 3
          - ITEM_NAVIGATION = 4
          - ITEM_VECTOR = 5
          - ITEM_FONT = 6
          - ITEM_VIDEO = 7
          - ITEM_AUDIO = 8
          - ITEM_DOCUMENT = 9
          - ITEM_COVER = 10

        We map type according to the extensions which are defined in ebooklib.EXTENSIONS.

        :Returns:
          Returns type of the item as number.
        """
        ...

    def get_content(self, default: bytes = b"") -> bytes:
        """
        Returns content of the item. Content should be of type 'str' (Python 2) or 'bytes' (Python 3)

        :Args:
          - default: Default value for the content if it is not already defined.

        :Returns:
          Returns content of the item.
        """
        ...

    def set_content(self, content: bytes) -> None:
        """
        Sets content value for this item.

        :Args:
          - content: Content value
        """
        ...

    def __str__(self) -> str: ...

class EpubNcx(EpubItem):
    "Represents Navigation Control File (NCX) in the EPUB."

    def __init__(self, uid: str = "ncx", file_name: str = "toc.ncx") -> None: ...
    def __str__(self) -> str: ...

class EpubCover(EpubItem):
    """
    Represents Cover image in the EPUB file.
    """

    def __init__(
        self, uid: str | None = None, file_name: str | None = None
    ) -> None: ...
    def get_type(self) -> Literal[10]: ...
    def __str__(self) -> str: ...

class EpubHtml(EpubItem):
    """
    Represents HTML document in the EPUB file.
    """

    _template_name: str
    title: str | None
    lang: str | None
    direction: str | None

    def __init__(
        self,
        uid: str | None = None,
        file_name: str | None = None,
        media_type: str = "application/xhtml+xml",
        content: bytes | None = None,
        title: str | None = None,
        lang: str | None = None,
        direction: str | None = None,
        media_overlay: str | None = None,
        media_duration: str | None = None,
    ) -> None: ...
    def is_chapter(self) -> bool:
        """
        Returns if this document is chapter or not.

        :Returns:
          Returns book value.
        """
        ...

    def get_type(self) -> Literal[9]:
        """
        Always returns ebooklib.ITEM_DOCUMENT as type of this document.

        :Returns:
          Always returns ebooklib.ITEM_DOCUMENT
        """
        ...

    def set_language(self, lang: str) -> None:
        """
        Sets language for this book item. By default it will use language of the book but it
        can be overwritten with this call.
        """
        ...

    def get_language(self) -> str | None:
        """
        Get language code for this book item. Language of the book item can be different from
        the language settings defined globaly for book.

        :Returns:
          As string returns language code.
        """
        ...

    def add_link(self, **kwargs: Any) -> None:
        """
        Add additional link to the document. Links will be embeded only inside of this document.

        >>> add_link(href='styles.css', rel='stylesheet', type='text/css')
        """
        ...

    def get_links(self) -> Generator[dict[str, str]]:
        """
        Returns list of additional links defined for this document.

        :Returns:
          As tuple return list of links.
        """
        ...

    def get_links_of_type(self, link_type: str) -> Generator[dict[str, str]]:
        """
        Returns list of additional links of specific type.

        :Returns:
          As tuple returns list of links.
        """
        ...

    def add_item(self, item: EpubItem) -> None:
        """
        Add other item to this document. It will create additional links according to the item type.

        :Args:
          - item: item we want to add defined as instance of EpubItem
        """
        ...

    def get_body_content(self) -> bytes:
        """
        Returns content of BODY element for this HTML document. Content will be of type 'str' (Python 2)
        or 'bytes' (Python 3).

        :Returns:
          Returns content of this document.
        """
        ...

    def get_content(self, default: bytes = b"") -> bytes:
        """
        Returns content for this document as HTML string. Content will be of type 'str' (Python 2)
        or 'bytes' (Python 3).

        :Args:
          - default: Default value for the content if it is not defined.

        :Returns:
          Returns content of this document.
        """
        ...

    def __str__(self) -> str: ...

class EpubCoverHtml(EpubHtml):
    """
    Represents Cover page in the EPUB file.
    """

    image_name: str

    def __init__(
        self,
        uid: str | None = None,
        file_name: str | None = None,
        image_name: str = "",
        title: str = "Cover",
    ) -> None: ...
    def is_chapter(self) -> Literal[False]:
        """
        Returns if this document is chapter or not.

        :Returns:
          Returns book value.
        """
        ...

    def get_content(self, default: bytes = b"") -> bytes:
        """
        Returns content for cover page as HTML string. Content will be of type 'str' (Python 2) or 'bytes' (Python 3).

        :Returns:
          Returns content of this document.
        """
        ...

    def __str__(self) -> str: ...

class EpubNav(EpubHtml):
    """
    Represents Navigation Document in the EPUB file.
    """

    def __init__(
        self,
        uid: str = "nav",
        file_name: str = "nav.xhtml",
        media_type: str = "application/xhtml+xml",
        title: str = "",
        direction: str | None = None,
    ) -> None: ...
    def is_chapter(self) -> Literal[False]:
        """
        Returns if this document is chapter or not.

        :Returns:
          Returns book value.
        """
        ...

    def __str__(self) -> str: ...

class EpubImage(EpubItem):
    """
    Represents Image in the EPUB file.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_type(self) -> Literal[1]: ...
    def __str__(self) -> str: ...

class EpubSMIL(EpubItem):
    def __init__(
        self,
        uid: str | None = None,
        file_name: str | None = None,
        content: bytes | None = None,
    ) -> None: ...
    def get_type(self) -> Literal[11]: ...
    def __str__(self) -> str: ...

class EpubBook:
    # Attributs d'instance
    spine: list[tuple[str, Literal["yes", "no"]]]  # List of (item_id, ...) tuples
    toc: list[Any]  # Table of contents structure

    def __init__(self) -> None: ...
    def reset(self) -> None:
        "Initialises all needed variables to default values"
        ...

    def set_identifier(self, uid: str) -> None:
        """
        Sets unique id for this epub

        :Args:
          - uid: Value of unique identifier for this book
        """
        ...

    def set_title(self, title: str) -> None:
        """
        Set title. You can set multiple titles.

        :Args:
          - title: Title value
        """
        ...

    def set_language(self, lang: str) -> None:
        """
        Set language for this epub. You can set multiple languages. Specific items in the book can have
        different language settings.

        :Args:
          - lang: Language code
        """
        ...

    def set_direction(self, direction: Literal["ltr", "rtl", "default"]) -> None:
        """
        :Args:
          - direction: Options are "ltr", "rtl" and "default"
        """
        ...

    def set_cover(
        self, file_name: str, content: bytes, create_page: bool = True
    ) -> None:
        """
        Set cover and create cover document if needed.

        :Args:
          - file_name: file name of the cover page
          - content: Content for the cover image
          - create_page: Should cover page be defined. Defined as bool value (optional). Default value is True.
        """
        ...

    def add_author(
        self,
        author: str,
        file_as: str | None = None,
        role: str | None = None,
        uid: str | None = None,
    ) -> None:
        "Add author for this document"
        ...

    def add_metadata(
        self,
        namespace: str,
        name: str,
        value: str,
        others: dict[str, str] | None = None,
    ) -> None:
        "Add metadata"
        ...

    def get_metadata(self, namespace: str, name: str) -> list[tuple[str, ...]]:
        "Retrieve metadata"
        ...

    def set_unique_metadata(
        self,
        namespace: str,
        name: str,
        value: str,
        others: dict[str, str] | None = None,
    ) -> None:
        "Add metadata if metadata with this identifier does not already exist, otherwise update existing metadata."
        ...

    def add_item(self, item: EpubItem) -> EpubItem:
        """
        Add additional item to the book. If not defined, media type and chapter id will be defined
        for the item.

        :Args:
          - item: Item instance
        """
        ...

    def get_item_with_id(self, uid: str) -> EpubItem | None:
        """
        Returns item for defined UID.

        >>> book.get_item_with_id('image_001')

        :Args:
          - uid: UID for the item

        :Returns:
          Returns item object. Returns None if nothing was found.
        """
        ...

    def get_item_with_href(self, href: str) -> EpubItem | None:
        """
        Returns item for defined HREF.

        >>> book.get_item_with_href('EPUB/document.xhtml')

        :Args:
          - href: HREF for the item we are searching for

        :Returns:
          Returns item object. Returns None if nothing was found.
        """
        ...

    def get_items(self) -> Generator[EpubItem]:
        """
        Returns all items attached to this book.

        :Returns:
          Returns all items as tuple.
        """
        ...

    def get_items_of_type(self, item_type: int) -> Generator[EpubItem]:
        """
        Returns all items of specified type.

        >>> book.get_items_of_type(epub.ITEM_IMAGE)

        :Args:
          - item_type: Type for items we are searching for

        :Returns:
          Returns found items as tuple.
        """
        ...

    def get_items_of_media_type(self, media_type: str) -> Generator[EpubItem]:
        """
        Returns all items of specified media type.

        :Args:
          - media_type: Media type for items we are searching for

        :Returns:
          Returns found items as tuple.
        """
        ...

    def set_template(self, name: str, value: bytes) -> None:
        """
        Defines templates which are used to generate certain types of pages. When defining new value for the template
        we have to use content of type 'str' (Python 2) or 'bytes' (Python 3).

        At the moment we use these templates:
          - ncx
          - nav
          - chapter
          - cover

        :Args:
          - name: Name for the template
          - value: Content for the template
        """
        ...

    def get_template(self, name: str) -> bytes | None:
        """
        Returns value for the template.

        :Args:
          - name: template name

        :Returns:
          Value of the template.
        """
        ...

    def add_prefix(self, name: str, uri: str) -> None:
        """
        Appends custom prefix to be added to the content.opf document

        >>> epub_book.add_prefix('bkterms', 'http://booktype.org/')

        :Args:
          - name: namespave name
          - uri: URI for the namespace
        """
        ...

class EpubWriter:
    DEFAULT_OPTIONS: dict[str, Any]

    def __init__(
        self, name: str | Path, book: EpubBook, options: dict[str, Any] | None = None
    ) -> None: ...
    def process(self) -> None: ...
    def write(self) -> None: ...

class EpubReader:
    DEFAULT_OPTIONS: dict[str, Any]

    def __init__(
        self, epub_file_name: str | Path, options: dict[str, Any] | None = None
    ) -> None: ...
    def process(self) -> None: ...
    def load(self) -> EpubBook: ...
    def read_file(self, name: str) -> bytes: ...

def write_epub(
    name: str | Path, book: EpubBook, options: dict[str, Any] | None = None
) -> bool:
    """
    Creates epub file with the content defined in EpubBook.

    >>> ebooklib.write_epub('book.epub', book)

    :Args:
      - name: file name for the output file
      - book: instance of EpubBook
      - options: extra opions as dictionary (optional)
    """
    ...

def read_epub(name: str | Path, options: dict[str, Any] | None = None) -> EpubBook:
    """
    Creates new instance of EpubBook with the content defined in the input file.

    >>> book = ebooklib.read_epub('book.epub')

    :Args:
      - name: full path to the input file
      - options: extra options as dictionary (optional)

    :Returns:
      Instance of EpubBook.
    """
    ...
