"""
This type stub file was generated by pyright.
"""

from typing import Any
from xml.etree.ElementTree import Element

# Variable globale pour l'initialisation des types MIME
mimetype_initialised: bool

def debug(obj: Any) -> None:
    """
    Debug utility function to print object information.

    Args:
        obj: Object to debug
    """
    ...

def parse_string(s: str | bytes) -> Element:
    """
    Parse XML string into an ElementTree Element.

    Args:
        s: XML string or bytes to parse

    Returns:
        Parsed XML Element
    """
    ...

def parse_html_string(s: str | bytes) -> Element:
    """
    Parse HTML string into an ElementTree Element.

    Args:
        s: HTML string or bytes to parse

    Returns:
        Parsed HTML Element
    """
    ...

def guess_type(extension: str) -> tuple[str | None, str | None]:
    """
    Guess MIME type based on file extension.

    Args:
        extension: File extension (with or without leading dot)

    Returns:
        Tuple of (mime_type, encoding), either can be None
    """
    ...

def create_pagebreak(pageref: str, label: str = "", html: str = "") -> str:
    """
    Create a pagebreak element for EPUB.

    Args:
        pageref: Page reference identifier
        label: Optional label for the pagebreak
        html: Optional HTML content for the pagebreak

    Returns:
        HTML string representing the pagebreak
    """
    ...

def get_headers(elem: Element) -> list[Element]:
    """
    Extract header elements from an XML/HTML element.

    Args:
        elem: XML/HTML Element to extract headers from

    Returns:
        List of header Elements (h1, h2, h3, etc.)
    """
    ...

def get_pages(item: Any) -> list[Any]:
    """
    Extract page information from an EPUB item.

    Args:
        item: EPUB item to extract pages from

    Returns:
        List of page objects
    """
    ...

def get_pages_for_items(items: list[Any]) -> list[Any]:
    """
    Extract page information from multiple EPUB items.

    Args:
        items: List of EPUB items to extract pages from

    Returns:
        Combined list of page objects from all items
    """
    ...
